# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c206f77a8716c5c3522182d876fcc94b"
name = "GTM-Extension-App"
handle = "gtm-extension-app-1"
application_url = "https://fabulous-influences-definitely-teachers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-test-store-dr.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://fabulous-influences-definitely-teachers.trycloudflare.com/auth/callback",
  "https://fabulous-influences-definitely-teachers.trycloudflare.com/auth/shopify/callback",
  "https://fabulous-influences-definitely-teachers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
